### PR TITLE
amirHosseinNajafizadeh9831065

### PR DESCRIPTION
**Pull request by amirhnajafiz**
Started

### CODE REVIEW

**Comment by amirhnajafiz** [comment]
This is 2nd session of workshop

**Comment by amirhnajafiz** [comment]
Added files via upload is for session 2
Added session 3 is for workshop session 3

**Review by RashadAnsari — DISMISSED** [review]
Approved but not much.

**Comment by RashadAnsari** [comment]
1- Where is you name and student number?
2- Your folder name is not valid.

**Comment by amirhnajafiz** [comment]
Is this good ? 
I just put them again.
Same files with new name, Are they correct ?

**Comment by amirhnajafiz** [comment]
And what do you mean by where is my Name and Student name ?
I wrote my name and student name in the pull request , Should i write them On the folders too ?
Cause I saw some of the students didn't.

**Comment by amirhnajafiz** [comment]
Sorry sir for the misunderstanding.
I've just resend the same files with correct name.
I did not change any file. Same files in new folder.
Is this correct ?

**Comment by amirhnajafiz** [comment]
My final folder is AmirHosseinNajafiZadeh9831065 in my last commit << Adding session 2 and 3
with correct name >>

**Comment by amirhnajafiz** [comment]
I just deleted the incorrect file names.

**Comment by amirhnajafiz** [comment]
Sorry sir for the misunderstanding.
I've just resend the same files with correct name.
I did not change any file. Same files in new folder.
Is this correct ?

**Comment by amirhnajafiz** [comment]
And I also deleted the same files that had invalid name.

**Comment by amirhnajafiz** [comment]
Sorry sir for the misunderstanding.
I've just resend the same files with correct name.
I did not change any file. Same files in new folder.

**Comment by alireza-pirhadi** [comment]
wrong implementation of timeTick method

**Comment by amirhnajafiz** [comment]
This method works correctly !!!!! 
What is wrong ?

**Pull request closed without merging**
